# ***************************************************************************************
# ***************************************************************************************
#
#      Name :      makeconfig.py
#      Authors :   Paul Robson (paul@robsons.org.uk)
#      Date :      19th December 2024
#      Reviewed :  No
#      Purpose :   Generate definitions file from environment variable parameter.
#
# ***************************************************************************************
# ***************************************************************************************

import sys,os,re

lines = [x.strip() for x in sys.argv[1][1:-1].split("|")]
print("// This file is automatically generated.\n\n")
print("\n".join(lines))
