//
//	This file is automatically generated.
//
#pragma once

#define FONT_COUNT (17)
#define FONT_MONO08 (0)
#define FONT_MONO10 (1)
#define FONT_MONO12 (2)
#define FONT_MONO14 (3)
#define FONT_MONO18 (4)
#define FONT_SANS08 (5)
#define FONT_SANS10 (6)
#define FONT_SANS12 (7)
#define FONT_SANS14 (8)
#define FONT_SANS18 (9)
#define FONT_SERIF08 (10)
#define FONT_SERIF10 (11)
#define FONT_SERIF12 (12)
#define FONT_SERIF14 (13)
#define FONT_SERIF18 (14)
#define FONT_TINY06 (15)
#define FONT_TINY07 (16)
